### PR TITLE
Update post processor

### PR DESCRIPTION
**Pull request by LucidityCrash**
Removing unused dc strings based on dcInputtype
Only converting kW to W based on the appropriate Power String

I'm not 100% happy with the way I've delt with the unused DC Strings but it works with the existing purge_if_unused function.

### CODE REVIEW

**Comment by LucidityCrash** [comment]
no somethings not right ... getting an error when restarting HA : 
2022-01-26 17:36:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140607904295856] Received invalid command: energy/info
2022-01-26 17:36:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140607904295856] Received invalid command: energy/info

**Comment by hultenvp** [comment]
Maybe ha does not like change of units on the dashboard?

**Comment by LucidityCrash** [comment]
yeah not changing units and actually my first version was doing exactly the same just without checking the unit string first.
really weird .... the errors looked repeatable on restart, I removed the calls to purge_if_unused for the dc strings and the error went away, put them back with some debug statements and still no errors errors over multiple restarts.

**Comment by hultenvp** [comment]
https://github.com/home-assistant/core/issues/54060

Seems to be related tot the recorder being confused by changing sensors? Anyway, seems to be going away aftr 2 hours.

Shall I merge this PR?

**Comment by LucidityCrash** [comment]
I've tried another restart this morning and no errors again, and nothing overnight.  So lets go for it.

**Pull request merged**
